image: maven:3.2.5-jdk-6

stages:
  - build
  - deploy

build_job:
  stage: build
  script: "mvn clean install verify -B -Dgpg.skip=true"

deploy_job:
  stage: deploy
  only:
    - tags
  script:
#  export/import GPG key - https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    - mvn clean deploy --settings .ci/settings.xml -B -U